---
# tasks file for ansible-role-consul-service

# consul reload seems to be missing /bin/kill when running molecule test
- name: Consul requirements
  ansible.builtin.package:
    name: procps
  failed_when: false

- name: Ensure Consul config directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ consul_config_dir }}"
    owner: consul
    group: bin
    mode: "0700"

- name: Check Consul bootstrapped file
  ansible.builtin.stat:
    path: /etc/consul/.consul_bootstrapped
  register: consul_service_bootstrapped_file
  changed_when: False

- name: Setup Consul agent
  ansible.builtin.include_role:
    name: brianshumate.consul
  vars:
    consul_dnsmasq_enable: false
  when: not consul_service_bootstrapped_file.stat.exists

- name: Define Consul service
  ansible.builtin.template:
    src: consul_service.json.j2
    dest: "{{ consul_config_dir }}/{{ consul_service_name }}.service.json"
    owner: consul
    group: bin
    mode: "0400"
  register: consul_service_definition
  when: not consul_service_deregister

- name: Remove Consul service
  ansible.builtin.file:
    path: "{{ consul_config_dir }}/{{ consul_service_name }}.service.json"
    state: absent
  register: consul_service_removal
  when: consul_service_deregister

- name: Reload Consul # noqa no-handler
  ansible.builtin.service:
    name: consul
    state: reloaded
  when: consul_service_definition.changed or consul_service_removal.changed
