---
- name: Converge
  hosts: molecule_consul_service
  become: yes

  vars:
    consul_node_role: bootstrap
    consul_group_name: molecule_consul_service
    consul_service_url4: test.local
    consul_service_tags:
      - testtag
      - published

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'
      tags: molecule-idempotence-notest

    - name: Check Nginx configuration directory
      ansible.builtin.stat:
        path: /etc/nginx
      register: consul_service_nginx_configuration_directory
      changed_when: False

    - name: Install nginx so default consul service health check is fine
      ansible.builtin.include_role:
        name: nginxinc.nginx
      when: not consul_service_nginx_configuration_directory.stat.exists

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
