---
- name: Converge
  hosts: molecule_consul_service
  become: yes

  vars:
    consul_node_role: bootstrap
    consul_service_url4: test.local
    consul_service_tags:
      - testtag
      - published

  roles:
    - role: wazo.consul_service
