---
- name: Prepare
  hosts: all
  become: yes

  tasks:
  - name: Set apt retries for debian <=12
    ansible.builtin.copy:
      dest: /etc/apt/apt.conf.d/99-retries.conf
      content: |
        Acquire::Retries "5";
      owner: root
      group: root
      mode: "0644"
    become: true
    when:
      - ansible_facts["distribution"] == "Debian"
      - ansible_facts["distribution_major_version"] | int <= 12

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install nginx so default consul service health check is fine
    ansible.builtin.include_role:
      name: geerlingguy.nginx
